### ISSUE TITLE
shortcode displays empty div

### ISSUE THREAD

**Issue by michael-lynch** [Shopify/buy-button-wordpress#1]
I just installed the plugin, connected my shop and added a product to a post. When the post is displayed, the shortcode renders as an empty div like this:

```
<div class="secp-embed secp-embed-product" data-embed_type="product" data-shop="eightysix-3.myshopify.com" data-product_handle="hoodie" data-display_size="compact" data-has_image="true" data-background_color="transparent" data-buy_button_out_of_stock_text="Out of Stock" data-buy_button_product_unavailable_text="Unavailable" data-show="all" data-show_product_price="true" data-show_product_title="true"></div>
```

My shop isn't currently live. It's a _Development Store_. Is that why the div is empty? Or am I missing something? I don't see any JS or PHP errors.

**Comment by danielpatricio** [comment]
@michael-lynch Sorry for the delay.

Are you using the plugin or did you copy the code from the Shopify admin? It looks like you removed the script that pulls in all the data.

**Comment by michael-lynch** [comment]
I'm using the plugin. I was able to add the shortcode to a post properly. I'm using my own custom theme, so I'm guessing something in my theme is blocking the script from loading in, but I have `wp_head()` and `wp_footer()` in my template, and I can see other scripts loading in. Any ideas?

**Comment by michael-lynch** [comment]
I've since updated the plugin. It works fine in the 2016 theme, but not in my own. I'm now getting this error:

`Call to undefined function cmb2_get_option() in /www/wp-content/plugins/shopify-ecommerce-shopping-cart/includes/class-output.php on line 163`

It would seem `cmb2` isn't working properly. Can you think of any reason why my theme may be preventing this function from being defined?
