### ISSUE TITLE
Buy-Button ignores all other customization

### ISSUE THREAD

**Issue by jimstrqc** [Shopify/buy-button-wordpress#8]
once i add the buy button to the wordpress, whatever is shown on wordpress is stripped from whatever modification i made on the shopify.

example:
(1) on shopify i can select the currency
(2) on wordpress there is no way to select the currency.

![screen shot 2016-10-25 at 16 47 35](https://cloud.githubusercontent.com/assets/20805100/19703731/e49881c4-9ad2-11e6-93d7-c970c1b20519.png)

![screen shot 2016-10-25 at 16 48 01](https://cloud.githubusercontent.com/assets/20805100/19703742/eea334e8-9ad2-11e6-9876-35f3fee99204.png)

**Comment by danielpatricio** [comment]
@jimstrqc Hi Jim, Is that an online store and an app in the top screenshot?
